app/Http/routes.php
<?php
// use App\User;
// use App\Role;
/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
// $router->get('/seed', function()
// {
  
//   $user = User::where('username', 'user')->first();

//   $role = Role::where('name','user')->first();
//   $user->assignRole($role);

// });
Route::get('/dailyAll',['middleware' => 'auth', 'uses'=>'ReportsController@dailyAll']);
Route::get('/monthlyAll',['middleware' => 'auth', 'uses'=>'ReportsController@monthlyAll']);
Route::get('/annualyAll',['middleware' => 'auth', 'uses'=>'ReportsController@annualyAll']);
Route::get('/daily',['middleware' => 'auth', 'uses'=>'ReportsController@daily']);
Route::get('/monthly',['middleware' => 'auth', 'uses'=>'ReportsController@monthly']);
Route::get('/annualy',['middleware' => 'auth', 'uses'=>'ReportsController@annualy']);
Route::get('/', ['middleware' => 'auth', 'uses'=>'HomeController@index','as'=>'root']);
Route::get('home', 'HomeController@index');
Route::get('position/getData', ['middleware' => 'auth', 'uses'=>'PositionController@getData']);
Route::get('office/getData', ['middleware' => 'auth', 'uses'=>'OfficeController@getData']);
Route::get('schedule/getData', ['middleware' => 'auth', 'uses'=>'ScheduleController@getData']);
Route::get('employee/getData', ['middleware' => 'auth', 'uses'=>'EmployeeController@getData']);
Route::resource('position', 'PositionController');
Route::resource('office', 'OfficeController');
Route::resource('schedule', 'ScheduleController');
Route::resource('employee', 'EmployeeController');
Route::resource('attendance', 'AttendanceController');

Route::controllers([
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
]);

resources/views/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Attendance Fingerprint Information System - ATFIS</title>
	
    <link href="{{ asset('/css/app.css')}}" rel="stylesheet">
    @yield('stylesheet')
		<link href="{{ asset('/css/style.css') }}" rel="stylesheet">

	<!-- Fonts -->
{{-- 	<link href='//fonts.googleapis.com/css?family=Roboto:400,300' rel='stylesheet' type='text/css'> --}}

	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
		<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
		<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->
</head>
<body>
	<nav class="navbar navbar-default navbar-fixed-top">
		<div class="container-fluid">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
					<span class="sr-only">Toggle Navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="#">ATFIS</a>
			</div>

			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav">
					<li><a href="{{ url('/') }}">Home</a></li>
				</ul>

				<ul class="nav navbar-nav navbar-right">
					@if (Auth::guest())
						<li><a href="{{ url('/auth/login') }}">Login</a></li>
						<li><a href="{{ url('/auth/register') }}">Register</a></li>
					@else
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">{{ Auth::user()->realname }} <span class="caret"></span></a>
							<ul class="dropdown-menu" role="menu">
								<li><a href="{{ url('/auth/logout') }}">Logout</a></li>
							</ul>
						</li>
					@endif
				</ul>
			</div>
		</div>
	</nav>

	@unless (Auth::guest())
	<div id="wrapper" class="active">
	<div id="sidebar-wrapper">
		<ul id="sidebar_menu" class="sidebar-nav">
		     <li class="sidebar-brand">
		     		<a id="menu-toggle" href="#">Menu<span id="main_icon" class="glyphicon glyphicon-align-justify"></span></a></li>
		</ul>
		@section('sidebar')
			@include('sidebar_view')
		@show
	</div>
		@yield('content')
	</div>
	@else
	<div id="wrapper">
		@yield('content')
	</div>
	@endunless

  <script src="{{ asset('/js/app.js') }}"></script>
  <script src="{{ asset('/js/dataTables.bootstrap.js') }}"></script>
  @yield('javascript')
  <script src="{{ asset('/js/script.js') }}"></script>
</body>
</html>

resources/views/home.blade.php
@extends('app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<div class="panel">
				<div class="panel-heading">Home</div>

				<div class="panel-body">

				<?php header("refresh:60;url=/") ?>
					You are logged in! {{ Auth::user()->realname}} 
					@if (Auth::user()->hasRole('user'))
					<hr>
						@if(count($attendances) ==0)
							<p class="alert alert-info info">Anda belum mengisi presensi masuk hari ini</p>
						@else
							<?php $i=0;
							foreach($attendances as $attendance)
							{
								$i += $attendance->in_out;
							}
						  ?>
							@if($i==0)
							<p class="alert alert-warning info">Anda belum mengisi presensi pulang hari ini</p>
							@endif
						@endif
						<p>Klik tombol untuk mengisi daftar kehadiran 
						<a href="#" url="{{ URL::route( 'attendance.store') }}" id="0" _token={{csrf_token()}} class="btn btn-info btn-sm btn-post"> <i class='fa fa-check'></i> Masuk</a> 
						<a href="#" url="{{ URL::route( 'attendance.store') }}" id="1" _token={{csrf_token()}} class="btn btn-warning btn-sm btn-post"> <i class='fa fa-check'></i> Pulang</a> </p>

						{{-- Attendance Form --}}
					  <div class="modal" id="attendanceModal">
					    <div class="modal-dialog">
					        <div class="modal-content">
					            <div class="modal-header">
					                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
					                <h4 class="modal-title">Daftar Hadir</h4>
					            </div>
					            <div class="modal-body">
					              <h4>Isi Presensi? </h4>
					            </div>
					            <div id="response"></div>
					            <div class="modal-footer">
					                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
					                <button type="button" class="btn btn-primary" id="save">Save</button>
					            </div>
					        </div>
					    </div>
					  </div>
					@endif
				</div>
			</div>
		</div>
	</div>
	@if (Auth::user()->hasRole('user'))
	<div class="row">
		<div class="col-md-6">
			<div class="panel">
				<div class="panel-heading">Jadwal</div>
				<div class="panel-body">
				<table class="table table-hover">
					<tr>
						<th>No</th>
						<th>Hari</th>
						<th>Masuk</th>
						<th>Pulang</th>
					</tr>
				@foreach ($schedules as $schedule)
					<tr>
						<td>1</td>
						<td>Senin</td>
						<td>{{$schedule->in_time}}</td>
						<td>{{$schedule->out_time}}</td>
					</tr>
										<tr>
						<td>2</td>
						<td>Selasa</td>
						<td>{{$schedule->in_time}}</td>
						<td>{{$schedule->out_time}}</td>
					</tr>
					<tr>
						<td>3</td>
						<td>Rabu</td>
						<td>{{$schedule->in_time}}</td>
						<td>{{$schedule->out_time}}</td>
					</tr>
					<tr>
						<td>4</td>
						<td>Kamis</td>
						<td>{{$schedule->in_time}}</td>
						<td>{{$schedule->out_time}}</td>
					</tr>
					<tr>
						<td>5</td>
						<td>Jumat</td>
						<td>{{$schedule->in_time}}</td>
						<td>{{$schedule->out_time}}</td>
					</tr>

				@endforeach
				</table>
				</div>
			</div>
		</div>
		<div class="col-md-6">
			<div class="panel">
				<div class="panel-heading">Log Absensi</div>
				<div class="panel-body">
				<table class="table table-hover" >
					<tr>
						<th>No</th>
						<th>Tanggal</th>
						<th>Jam</th>
						<th>Keterangan</th>
					</tr>
					<tbody id="log">
					<?php $i = 1 ?>
					@foreach ($attendances as $attendance)
					<tr>
						<td>{{$i}}</td>
						<td>{{date('d-m-Y',strtotime($attendance->date))}}</td>
						<td>{{$attendance->time}}</td>
						<td>{{ $attendance->in_out =='0' ? 'Masuk' : 'Pulang' }}</td>
					</tr>
					<?php $i++ ?>
					@endforeach
					</tbody>
				</table>
				</div>
			</div>
		</div>
	</div>
	@endif
</div>
@endsection

resources/views/sidebar_view.blade.php
<ul class="metismenu sidebar-nav" id="sidebar">

  @if (Auth::user()->hasRole('administrator'))
  <li>
    <a href="#">Master<span class="sub_icon fa fa-file"></span></a>
    <ul class="sidebar-sub-nav">
      <li><a href="employee" class="link_active">Pegawai<span class="sub_icon fa fa-users"></span></a></li>
      <li><a href="position">Jabatan<span class="sub_icon fa fa-briefcase"></span></a></li>
      <li><a href="office">Kantor<span class="sub_icon fa fa-building-o"></span></a></li>
      <li><a href="schedule">Jadwal<span class="sub_icon fa fa-calendar"></span></a></li>
    </ul>
  </li>
 <li>
    <a href="#">Laporan<span class="sub_icon fa fa-bar-chart"></span></a>
    <ul class="sidebar-sub-nav">
      <li><a href="dailyAll">Harian<span class="sub_icon fa fa-calendar"></span></a></li>
      <li><a href="monthlyAll">Bulanan<span class="sub_icon fa fa-calendar"></span></a></li>
      <li><a href="annualyAll">Tahunan<span class="sub_icon fa fa-calendar"></span></a></li>
    </ul>
  </li>
    @elseif (Auth::user()->hasRole('user'))
  <li>
    <a href="#">Laporan<span class="sub_icon fa fa-bar-chart"></span></a>
    <ul class="sidebar-sub-nav">
      <li><a href="daily">Harian<span class="sub_icon fa fa-calendar"></span></a></li>
      <li><a href="monthly">Bulanan<span class="sub_icon fa fa-calendar"></span></a></li>
      <li><a href="annualy">Tahunan<span class="sub_icon fa fa-calendar"></span></a></li>
    </ul>
  </li> 
    @endif
   

</ul>