app/Http/routes.php
<?php
// use App\User;
// use App\Role;
/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
// $router->get('/seed', function()
// {
  
//   $user = User::where('username', 'user')->first();

//   $role = Role::where('name','user')->first();
//   $user->assignRole($role);

// });
Route::get('/dailyAll',['middleware' => 'auth', 'uses'=>'ReportsController@dailyAll']);
Route::get('/monthlyAll',['middleware' => 'auth', 'uses'=>'ReportsController@monthlyAll']);
Route::get('/annualyAll',['middleware' => 'auth', 'uses'=>'ReportsController@annualyAll']);
Route::get('/daily',['middleware' => 'auth', 'uses'=>'ReportsController@daily']);
Route::get('/monthly',['middleware' => 'auth', 'uses'=>'ReportsController@monthly']);
Route::get('/annualy',['middleware' => 'auth', 'uses'=>'ReportsController@annualy']);
Route::get('/', ['middleware' => 'auth', 'uses'=>'HomeController@index','as'=>'root']);
Route::get('home', 'HomeController@index');
Route::get('position/getData', ['middleware' => 'auth', 'uses'=>'PositionController@getData']);
Route::get('office/getData', ['middleware' => 'auth', 'uses'=>'OfficeController@getData']);
Route::get('schedule/getData', ['middleware' => 'auth', 'uses'=>'ScheduleController@getData']);
Route::get('employee/getData', ['middleware' => 'auth', 'uses'=>'EmployeeController@getData']);
Route::resource('position', 'PositionController');
Route::resource('office', 'OfficeController');
Route::resource('schedule', 'ScheduleController');
Route::resource('employee', 'EmployeeController');
Route::resource('attendance', 'AttendanceController');

Route::controllers([
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
]);

app/Position.php
<?php namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Employee;

class Position extends Model {

	public function employees(){
    return $this->hasMany('Employee');
  }

}

app/Http/Controllers/PositionController.php
<?php namespace App\Http\Controllers;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Input;
use Illuminate\Http\Request;
use App\Position;
use Datatables;

class PositionController extends Controller {

	/**
	 * Create a new controller instance.
	 *
	 * @return void
	 */
	public function __construct()
	{
		$this->middleware('auth');
	}

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		return view('position/index');
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		return view('position/create');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param Request $request
	 * @return Response
	 */
	public function store(Request $request)
	{
		$v = Validator::make($request->all(), [
 			'name' => 'required|unique:positions'
		]);
		

		if ($v->passes()) {
			$position     = new Position();
			$position->name = Input::get('name');
			$position->created_at = date('Y-m-d H:i:s');

			if($position->save())
			{            
	 		 $message = array(array("message"=>"Data was saved"));
	 		 return json_encode($message);
      }
 		}else{
 			$message = json_encode( $v->messages());
		 	return $message;
 		}
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		//
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$position = Position::find($id);

		return view('position/edit')
			->with('position', $position);
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param Request $request
	 * @return Response
	 */
	public function update(Request $request)
	{
		$v = Validator::make($request->all(), [
 			'name' => 'required|unique:positions'
		]);
		

		if ($v->passes()) {
			$position     = Position::find(Input::get('id'));
			$position->name = Input::get('name');
			$position->updated_at = date('Y-m-d H:i:s');

			if($position->save())
			{            
	 		 $message = array(array("message"=>"Data was update"));
	 		 return json_encode($message);
      }
 		}else{
 			$message = json_encode( $v->messages());
		 	return $message;
 		}
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$position = Position::find($id);
		if($position->delete())
			{            
	 		 $message = array(array("message"=>"Data was deleted"));
	 		 return json_encode($message);
      }
	}

	 public function getData()
    {
        $positions = Position::all();

        return Datatables::of($positions)
        ->addColumn('operations','<a href="#" url="{{ URL::route( \'position.edit\', array( $id )) }}"class=\'btn btn-xs btn-info btn-edit\' ><i class=\'fa fa-edit\'></i>Edit</a> &nbsp; 
        	<a data="#" url="{{ URL::route( \'position.destroy\', array( $id )) }} "class=\'btn btn-xs btn-danger btn-destroy\' id=\'{{$id}}\' _token={{csrf_token()}}><i class=\'fa fa-close\'></i>Delete</a>')
        ->make(true);
    }

}

resources/views/position/create.blade.php
<form action="{{URL::to('position')}}" class="form-horizontal" id="newForm">
<input name="_method" type="hidden" value="POST">
<input type="hidden" name="_token" value="<?php echo csrf_token(); ?>">
  <div class="form-group">
    <label for="name" class="col-sm-2 control-label">Nama</label>
    <div class="col-sm-10">
      <input type="text" class="form-control" id="name" placeholder="Nama Jabatan"  name="name" required>
    </div>
  </div>
</form>

resources/views/position/edit.blade.php
<form action="{{ URL::route( 'position.update', array( $position->id )) }}"  class="form-horizontal" id="newForm">
<input type="hidden" name="_token" value="<?php echo csrf_token(); ?>">
<input name="_method" type="hidden" value="PUT">
  <div class="form-group">
    <label for="name" class="col-sm-2 control-label">Nama</label>
    <div class="col-sm-10">
      <input type="hidden" name="id" value="{{$position->id}}">
      <input type="text" class="form-control" id="name" placeholder="Nama Jabatan"  name="name" value="{{$position->name}}" required>
    </div>
  </div>
</form>

resources/views/position/index.blade.php
@extends('app')

@section('content')
  <div class="row">
      <h2 class="page-header">Master Data <small>- Jabatan</small></h2>
      <p><a href="#" class="btn btn-sm btn-primary" id="btn-new">Tambah Jabatan</a></p>
  </div>
  {{-- Datatable --}}
  <table id="users-table" class="table table-condensed">
    <thead>
    <tr>
        <th>Id</th>
        <th>Name</th>
        <th>Operation</th>
    </tr>
    </thead>
  </table>
  
  {{-- Modal Form --}}
  <div class="modal" id="myModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title">Master Jabatan</h4>
            </div>
            <div class="modal-body"></div>
            <div id="response"></div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" id="save">Save changes</button>
            </div>
        </div>
    </div>
  </div>

  {{-- Delete Form --}}
  <div class="modal" id="deleteModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title">Master Jabatan</h4>
            </div>
            <div class="modal-body">
              <h4>Are you sure ?</h4>
            </div>
            <div id="response"></div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-danger" id="delete">Delete</button>
            </div>
        </div>
    </div>
  </div>

@endsection

@section('javascript')
<script>
  var table = $('#users-table').DataTable({
      processing: true,
      serverSide: true,
      ajax: '{{ url("position/getData") }}',
      columns: [
          {data: 'id', name: 'id'},
          {data: 'name', name: 'name'},
          {data: 'operations', name: 'operations'},
      ]
  });
  table.ajax.reload();
</script>
@endsection