app/Http/routes.php
<?php
// use App\User;
// use App\Role;
/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
// $router->get('/seed', function()
// {
  
//   $user = User::where('username', 'user')->first();

//   $role = Role::where('name','user')->first();
//   $user->assignRole($role);

// });
Route::get('/dailyAll',['middleware' => 'auth', 'uses'=>'ReportsController@dailyAll']);
Route::get('/monthlyAll',['middleware' => 'auth', 'uses'=>'ReportsController@monthlyAll']);
Route::get('/annualyAll',['middleware' => 'auth', 'uses'=>'ReportsController@annualyAll']);
Route::get('/daily',['middleware' => 'auth', 'uses'=>'ReportsController@daily']);
Route::get('/monthly',['middleware' => 'auth', 'uses'=>'ReportsController@monthly']);
Route::get('/annualy',['middleware' => 'auth', 'uses'=>'ReportsController@annualy']);
Route::get('/', ['middleware' => 'auth', 'uses'=>'HomeController@index','as'=>'root']);
Route::get('home', 'HomeController@index');
Route::get('position/getData', ['middleware' => 'auth', 'uses'=>'PositionController@getData']);
Route::get('office/getData', ['middleware' => 'auth', 'uses'=>'OfficeController@getData']);
Route::get('schedule/getData', ['middleware' => 'auth', 'uses'=>'ScheduleController@getData']);
Route::get('employee/getData', ['middleware' => 'auth', 'uses'=>'EmployeeController@getData']);
Route::resource('position', 'PositionController');
Route::resource('office', 'OfficeController');
Route::resource('schedule', 'ScheduleController');
Route::resource('employee', 'EmployeeController');
Route::resource('attendance', 'AttendanceController');

Route::controllers([
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
]);

app/Schedule.php
<?php namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Employee;
class Schedule extends Model {

	public function employees(){
    return $this->hasMany('App\Employee');
  }

}

app/Http/Controllers/ScheduleController.php
<?php namespace App\Http\Controllers;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Input;
use Illuminate\Http\Request;
use App\Schedule;
use Datatables;

class ScheduleController extends Controller {

	/**
	 * Create a new controller instance.
	 *
	 * @return void
	 */
	public function __construct()
	{
		$this->middleware('auth');
	}

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		return view('schedule/index');
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		return view('schedule/create');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param Request $request
	 * @return Response
	 */
	public function store(Request $request)
	{
		$v = Validator::make($request->all(), [
 			'code' => 'required|unique:schedules',
 			'in_time'=>'required',
 			'out_time'=>'required'
		]);
		

		if ($v->passes()) {
			$schedule     = new Schedule();
			$schedule->code = $request->input('code');
			$schedule->day = $request->input('day');
			$schedule->in_time = $request->input('in_time');
			$schedule->out_time = $request->input('out_time');
			$schedule->created_at = date('Y-m-d H:i:s');

			if($schedule->save())
			{            
	 		 $message = array(array("message"=>"Data was saved"));
	 		 return json_encode($message);
      }
 		}else{
 			$message = json_encode( $v->messages());
		 	return $message;
 		}
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		//
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$schedule = Schedule::find($id);

		return view('schedule/edit')
			->with('schedule', $schedule);
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param Request $request
	 * @return Response
	 */
	public function update(Request $request)
	{
		$v = Validator::make($request->all(), [
 			'code' => 'required',
 			'in_time'=>'required',
 			'out_time'=>'required'
		]);
		

		if ($v->passes()) {
			$schedule     = Schedule::find($request->input('id'));
			$schedule->code = $request->input('code');
			$schedule->day = $request->input('day');
			$schedule->in_time = $request->input('in_time');
			$schedule->out_time = $request->input('out_time');
			$schedule->created_at = date('Y-m-d H:i:s');

			if($schedule->save())
			{            
	 		 $message = array(array("message"=>"Data was update"));
	 		 return json_encode($message);
      }
 		}else{
 			$message = json_encode( $v->messages());
		 	return $message;
 		}
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$schedule = Schedule::find($id);
		if($schedule->delete())
			{            
	 		 $message = array(array("message"=>"Data was deleted"));
	 		 return json_encode($message);
      }
	}

	 public function getData()
    {
        $schedules = Schedule::all();

        return Datatables::of($schedules)
        ->addColumn('operations','<a href="#" url="{{ URL::route( \'schedule.edit\', array( $id )) }}"class=\'btn btn-xs btn-info btn-edit\' ><i class=\'fa fa-edit\'></i>Edit</a> &nbsp; 
        	<a data="#" url="{{ URL::route( \'schedule.destroy\', array( $id )) }} "class=\'btn btn-xs btn-danger btn-destroy\' id=\'{{$id}}\' _token={{csrf_token()}}><i class=\'fa fa-close\'></i>Delete</a>')
        ->make(true);
    }

}

resources/views/schedule/create.blade.php
<form action="{{URL::to('schedule')}}" class="form-horizontal" id="newForm">
<input name="_method" type="hidden" value="POST">
<input type="hidden" name="_token" value="<?php echo csrf_token(); ?>">
  <div class="form-group">
    <label for="code" class="col-sm-2 control-label">Kode </label>
    <div class="col-sm-10">
      <input type="text" class="form-control" id="code" placeholder="Kode Jadwal"  name="code" required>
    </div>
  </div>
  <div class="form-group">
    <label for="day" class="col-sm-2 control-label">Hari </label>
    <div class="col-sm-10">
      <select name="day" id="day" class="form-control">
        <option value="1">Minggu</option>
        <option value="2">Senin</option>
        <option value="3">Selasa</option>
        <option value="4">Rabu</option>
        <option value="5">Kamis</option>
        <option value="6">Jumat</option>
        <option value="7">Sabtu</option>
      </select>
    </div>
  </div>
  <div class="form-group">
    <label for="in_time" class="col-sm-2 control-label" >Waktu Masuk</label>
    <div class="col-sm-10">
      <input type="text" class="form-control timepicker" id="in_time" placeholder="JJ:MM:DD" name="in_time" required>
    </div>
  </div>
  <div class="form-group">
    <label for="out_time" class="col-sm-2 control-label">Waktu Keluar</label>
    <div class="col-sm-10">
      <input type="text" class="form-control timepicker" id="out_time" name="out_time" placeholder="JJ:MM:DD" required>
    </div>
  </div>
</form>
<script>
  $('#in_time').val('00:00:00');
  $('#out_time').val( moment().format("00:00:00"));
  $('#in_time').datetimepicker({locale:'id',format: 'HH:mm:ss'});
  $('#out_time').datetimepicker({locale:'id',format: 'HH:mm:ss'});

</script>

resources/views/schedule/edit.blade.php
<form action="{{URL::route('schedule.update',array($schedule->id))}}" class="form-horizontal" id="newForm">
<input name="_method" type="hidden" value="PUT">
<input type="hidden" name="_token" value="<?php echo csrf_token(); ?>">
  <div class="form-group">
    <label for="code" class="col-sm-2 control-label">Kode </label>
    <div class="col-sm-10">
          <input type="hidden" name="id" value="{{$schedule->id}}">
      <input type="text" class="form-control" id="code" placeholder="Kode Jadwal"  name="code" value="{{$schedule->code}}" required>
    </div>
  </div>
  <div class="form-group">
    <label for="day" class="col-sm-2 control-label">Hari </label>
    <div class="col-sm-10">
      <select name="day" id="day" class="form-control">
        <option value="1" {{($schedule->day == 1)? 'selected' : '' }} >Minggu</option>
        <option value="2" {{($schedule->day == 2)? 'selected' : '' }}>Senin</option>
        <option value="3" {{($schedule->day == 3)? 'selected' : '' }}>Selasa</option>
        <option value="4" {{($schedule->day == 4)? 'selected' : '' }}>Rabu</option>
        <option value="5" {{($schedule->day == 5)? 'selected' : '' }}>Kamis</option>
        <option value="6" {{($schedule->day == 6)? 'selected' : '' }}>Jumat</option>
        <option value="7" {{($schedule->day == 7)? 'selected' : '' }}>Sabtu</option>
      </select>
    </div>
  </div>
  <div class="form-group">
    <label for="in_time" class="col-sm-2 control-label" >Waktu Masuk</label>
    <div class="col-sm-10">
      <input type="text" class="form-control timepicker" id="in_time" placeholder="JJ:MM:DD" name="in_time" value="{{$schedule->in_time}}" required>
    </div>
  </div>
  <div class="form-group">
    <label for="out_time" class="col-sm-2 control-label">Waktu Keluar</label>
    <div class="col-sm-10">
      <input type="text" class="form-control timepicker" id="out_time" name="out_time" placeholder="JJ:MM:DD" value="{{$schedule->out_time}}" required>
    </div>
  </div>
</form>
<script>
  $('#in_time').datetimepicker({locale:'id',format: 'HH:mm:ss'});
  $('#out_time').datetimepicker({locale:'id',format: 'HH:mm:ss'});
</script>

resources/views/schedule/index.blade.php
@extends('app')

@section('content')
  <div class="row">
      <h2 class="page-header">Master Data <small>- Jadwal</small></h2>
      <p><a href="#" class="btn btn-sm btn-primary" id="btn-new">Tambah Jadwal</a></p>
  </div>
  {{-- Datatable --}}
  <table id="users-table" class="table table-condensed">
    <thead>
    <tr>
        <th>Id</th>
        <th>Kode</th>
        <th>Hari</th>
        <th>Jam Masuk</th>
        <th>Jam Keluar</th>
        <th>Operation</th>
    </tr>
    </thead>
  </table>
  
  {{-- Modal Form --}}
  <div class="modal" id="myModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title">Master Jabatan</h4>
            </div>
            <div class="modal-body"></div>
            <div id="response"></div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" id="save">Save changes</button>
            </div>
        </div>
    </div>
  </div>

  {{-- Delete Form --}}
  <div class="modal" id="deleteModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title">Master Jadwal</h4>
            </div>
            <div class="modal-body">
              <h4>Are you sure ?</h4>
            </div>
            <div id="response"></div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-danger" id="delete">Delete</button>
            </div>
        </div>
    </div>
  </div>

@endsection

@section('javascript')
  <script>
  var table = $('#users-table').DataTable({
      processing: true,
      serverSide: true,
      ajax: '{{ url("schedule/getData") }}',
      columns: [
          {data: 'id', name: 'id'},
          {data: 'code', name: 'code'},
          {data: 'day', name: 'day'},
          {data: 'in_time', name: 'in_time'},
          {data: 'out_time', name: 'out_time'},
          {data: 'operations', name: 'operations'},
      ]
  });
  table.ajax.reload();
</script>
@endsection