app/Http/routes.php
<?php
// use App\User;
// use App\Role;
/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
// $router->get('/seed', function()
// {
  
//   $user = User::where('username', 'user')->first();

//   $role = Role::where('name','user')->first();
//   $user->assignRole($role);

// });
Route::get('/dailyAll',['middleware' => 'auth', 'uses'=>'ReportsController@dailyAll']);
Route::get('/monthlyAll',['middleware' => 'auth', 'uses'=>'ReportsController@monthlyAll']);
Route::get('/annualyAll',['middleware' => 'auth', 'uses'=>'ReportsController@annualyAll']);
Route::get('/daily',['middleware' => 'auth', 'uses'=>'ReportsController@daily']);
Route::get('/monthly',['middleware' => 'auth', 'uses'=>'ReportsController@monthly']);
Route::get('/annualy',['middleware' => 'auth', 'uses'=>'ReportsController@annualy']);
Route::get('/', ['middleware' => 'auth', 'uses'=>'HomeController@index','as'=>'root']);
Route::get('home', 'HomeController@index');
Route::get('position/getData', ['middleware' => 'auth', 'uses'=>'PositionController@getData']);
Route::get('office/getData', ['middleware' => 'auth', 'uses'=>'OfficeController@getData']);
Route::get('schedule/getData', ['middleware' => 'auth', 'uses'=>'ScheduleController@getData']);
Route::get('employee/getData', ['middleware' => 'auth', 'uses'=>'EmployeeController@getData']);
Route::resource('position', 'PositionController');
Route::resource('office', 'OfficeController');
Route::resource('schedule', 'ScheduleController');
Route::resource('employee', 'EmployeeController');
Route::resource('attendance', 'AttendanceController');

Route::controllers([
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
]);

app/Employee.php
<?php namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Position;
use App\Office;
use App\Schedule;

class Employee extends Model {

	protected $fillable = [];

  public function position(){
    return $this->belongsTo('App\Position');
  }

  public function office(){
    return $this->belongsTo('App\Office');
  }

  public function schedule(){
    return $this->belongsTo('App\Schedule');
  }

  public function attendances(){
    return $this->hasMany('App\Attendance');
  }

}

app/Http/Controllers/EmployeeController.php
<?php namespace App\Http\Controllers;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Input;
use Illuminate\Http\Request;
use App\Employee;
use App\Position;
use App\Office;
use App\Schedule;
use App\User;
use App\Role;
use Datatables;

class EmployeeController extends Controller {

	/**
	 * Create a new controller instance.
	 *
	 * @return void
	 */
	public function __construct()
	{
		$this->middleware('auth');
	}

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		return view('employee/index');
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		$positions = Position::select(['id','name'])->get();
		$offices = Office::select(['id','name'])->get();
		$schedules = Schedule::select(['id','code'])->get();
		return view('employee/create',array('positions'=>$positions,'offices'=>$offices,'schedules'=>$schedules));
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param Request $request
	 * @return Response
	 */
	public function store(Request $request)
	{
		$messages = [
    'nik.required' => 'Kolom Nomor Induk harus di isi.',
    'name.required' => 'Kolom Nama harus di isi.',
    'place_of_birth.required' => 'Kolom Tempat Lahir harus di isi.',
    'birthday.required' => 'Kolom Tanggal Lahir harus di isi.',
    'address.required' => 'Kolom Alamat harus di isi.',
    'phone.required' => 'Kolom Nomor Telepon harus di isi.',
    'email.required' => 'Kolom Email harus di isi.',
    'position_id.required' => 'Kolom Jabatan harus di pilih.',
    'office_id.required' => 'Kolom Kantor harus di pilih.',
    'schedule_id.required' => 'Kolom Jadwal harus di pilih.',
		];
		$v = Validator::make($request->all(), [
 			'nik' => 'required|unique:employees',
 			'name'=>'required',
 			'place_of_birth'=>'required',
 			'birthday'=>'required',
 			'address'=>'required',
 			'phone'=>'required',
 			'email'=>'required|email|unique:employees',
			'position_id'=>'required|digits_between:1,100',
			'office_id'=>'required|digits_between:1,100',
			'schedule_id'=>'required|digits_between:1,100',
		],$messages);

		if ($v->passes()) {
			$employee     = new Employee();
			$employee->nik = $request->input('nik');
			$employee->name = $request->input('name');
			$employee->place_of_birth = $request->input('place_of_birth');
			$employee->birthday = \DateTime::createFromFormat('j:m:Y',$request->input('birthday'));
			$employee->address = $request->input('address');
			$employee->phone = $request->input('phone');
			$employee->email = $request->input('email');
			$employee->position_id = $request->input('position_id');
			$employee->office_id = $request->input('office_id');
			$employee->schedule_id = $request->input('schedule_id');
			if (!$request->input('active')) {
				$employee->active=0;
			}else{
				$employee->active = $request->input('active');	
			}
			$employee->created_at = date('Y-m-d H:i:s');

			if($request->input('register')){
					$user = new User();
					$user->username = $request->input('nik');
					$user->realname = $request->input('name');
					$user->email = $request->input('email');
					$user->password =  \Hash::make($request->input('nik'));

					if($employee->save() && $user->save())
					{
						$role = Role::where('name','user')->first();
						$user->assignRole($role);            
						$message = array(array("message"=>"Data was saved"));
						return json_encode($message);
					}
			}else{
				if($employee->save())
				{            
					$message = array(array("message"=>"Data was saved"));
					return json_encode($message);
				}
			}

 		}else{
 			$message = json_encode( $v->messages());
		 	return $message;
 		}
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$employee = Employee::find($id);

		return view('employee.show')
			->with('employee', $employee);
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$employee = Employee::find($id);
		$positions = Position::select(['id','name'])->get();
		$offices = Office::select(['id','name'])->get();
		$schedules = Schedule::select(['id','code'])->get();
		return view('employee/edit')
			->with('employee', $employee)
			->with('positions', $positions)
			->with('offices', $offices)
			->with('schedules', $schedules);
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param Request $request
	 * @return Response
	 */
	public function update(Request $request)
	{
		$messages = [
    'name.required' => 'Kolom Nama harus di isi.',
    'place_of_birth.required' => 'Kolom Tempat Lahir harus di isi.',
    'birthday.required' => 'Kolom Tanggal Lahir harus di isi.',
    'address.required' => 'Kolom Alamat harus di isi.',
    'phone.required' => 'Kolom Nomor Telepon harus di isi.',
    'email.required' => 'Kolom Email harus di isi.',
    'position_id.required' => 'Kolom Jabatan harus di pilih.',
    'office_id.required' => 'Kolom Kantor harus di pilih.',
    'schedule_id.required' => 'Kolom Jadwal harus di pilih.',
		];
		$v = Validator::make($request->all(), [
 			'name'=>'required',
 			'place_of_birth'=>'required',
 			'birthday'=>'required',
 			'address'=>'required',
 			'phone'=>'required',
 			'email'=>'required|email',
			'position_id'=>'required|digits_between:1,100',
			'office_id'=>'required|digits_between:1,100',
			'schedule_id'=>'required|digits_between:1,100',
		],$messages);

		if ($v->passes()) {
			$employee     = Employee::find($request->input('id'));
			$employee->nik = $request->input('nik');
			$employee->name = $request->input('name');
			$employee->place_of_birth = $request->input('place_of_birth');
			$employee->birthday = \DateTime::createFromFormat('j:m:Y',$request->input('birthday'));
			$employee->address = $request->input('address');
			$employee->phone = $request->input('phone');
			$employee->email = $request->input('email');
			$employee->position_id = $request->input('position_id');
			$employee->office_id = $request->input('office_id');
			$employee->schedule_id = $request->input('schedule_id');
			if (!$request->input('active')) {
				$employee->active=0;
			}else{
				$employee->active = $request->input('active');	
			}
			$employee->updated_at = date('Y-m-d H:i:s');

			if($employee->save())
			{            
	 		 $message = array(array("message"=>"Data was saved"));
	 		 return json_encode($message);
      }
 		}else{
 			$message = json_encode( $v->messages());
		 	return $message;
 		}
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$employee = Employee::find($id);
		$name = $employee->nik;
		$user = User::where('username','=',$name)->first();
		if ($user) {
			if($employee->delete() && $user->delete() ){
				$message = array(array("message"=>"Data was deleted"));
				return json_encode($message);
			}else{
				$message = array(array("message"=>"Ouups error was found"));
				return json_encode($message);
			}
		}else{
			if($employee->delete()){
				$message = array(array("message"=>"Data was deleted"));
				return json_encode($message);
			}
		}

	}

	 public function getData()
    {
        // $employees = Employee::all();
    	$employees = Employee::join('positions', 'employees.position_id', '=', 'positions.id')
    				->join('offices', 'employees.office_id', '=', 'offices.id')
    				->join('schedules', 'employees.schedule_id', '=', 'schedules.id')
            ->select(['employees.id','employees.nik','employees.name','employees.active AS active','positions.name AS position', 'offices.name AS office','schedules.code AS schedule']);
        return Datatables::of($employees)
        ->editColumn('nik', function ($employee) {
                return '<a href="#" url="employee/'.$employee->id.'"class=\'btn-show\' >'.$employee->nik.'</a>';
            })
        ->editColumn('active', function ($employee) {
								$active=($employee->active ==0) ? '<span class=\'label label-danger\'>Not Active</span>' : '<span class=\'label label-success\'>Active</span>' ;
                return $active;
            })
        ->addColumn('operations','<a href="#" url="{{ URL::route( \'employee.edit\', array( $id )) }}"class=\'btn btn-xs btn-info btn-edit\' ><i class=\'fa fa-edit\'></i>Edit</a> &nbsp; 
        	<a data="#" url="{{ URL::route( \'employee.destroy\', array( $id )) }} "class=\'btn btn-xs btn-danger btn-destroy\' id=\'{{$id}}\' _token={{csrf_token()}}><i class=\'fa fa-close\'></i>Delete</a>')
        ->make(true);
    }

}

resources/views/employee/create.blade.php
<form action="{{URL::to('employee')}}" class="form-horizontal" id="newForm">
<input name="_method" type="hidden" value="POST">
<input type="hidden" name="_token" value="<?php echo csrf_token(); ?>">
  <div class="form-group">
    <label for="nik" class="col-sm-2 control-label">Nomor Induk </label>
    <div class="col-sm-10">
      <input type="text" class="form-control" id="nik" placeholder="Nomor Induk Pegawai"  name="nik" required>
    </div>
  </div>
  <div class="form-group">
    <label for="name" class="col-sm-2 control-label">Nama </label>
    <div class="col-sm-10">
      <input type="text" class="form-control" id="name" placeholder="Nama Pegawai"  name="name" required>
    </div>
  </div>
  <div class="form-group">
    <label for="place_of_birth" class="col-sm-2 control-label">Tempat Lahir </label>
    <div class="col-sm-10">
      <input type="text" class="form-control" id="place_of_birth" placeholder="Tempat Lahir"  name="place_of_birth" required>
    </div>
  </div>
  <div class="form-group">
    <label for="birthday" class="col-sm-2 control-label">Tanggal Lahir </label>
    <div class="col-sm-10">
      <input type="text" class="form-control" id="birthday" placeholder="Tanggal Lahir"  name="birthday" required>
    </div>
  </div>
  <div class="form-group">
    <label for="address" class="col-sm-2 control-label">Alamat </label>
    <div class="col-sm-10">
      <textarea name="address" id="address" cols="30" rows="5" class="form-control" required></textarea>
    </div>
  </div>
  <div class="form-group">
    <label for="phone" class="col-sm-2 control-label">Telepon </label>
    <div class="col-sm-10">
      <input type="text" class="form-control" id="phone" placeholder="Nomor Telp"  name="phone" required>
    </div>
  </div>
  <div class="form-group">
    <label for="email" class="col-sm-2 control-label">Email </label>
    <div class="col-sm-10">
      <input type="email" class="form-control" id="email" placeholder="Email Pegawai"  name="email" required>
    </div>
  </div>
  <div class="form-group">
    <label for="position" class="col-sm-2 control-label">Jabatan</label>
    <div class="col-sm-10">
      <select name="position_id" id="position" class="form-control">
        <option value="0">--Pilih Jabatan--</option>
        @foreach ($positions as $position)
            <option value="{{$position->id}}">{{$position->name}}</option>
        @endforeach
      </select>
    </div>
  </div>
  <div class="form-group">
    <label for="office" class="col-sm-2 control-label">Kantor</label>
    <div class="col-sm-10">
      <select name="office_id" id="office" class="form-control">
        <option value="0">--Pilih Kantor--</option>
        @foreach ($offices as $office)
            <option value="{{$office->id}}">{{$office->name}}</option>
        @endforeach
      </select>
    </div>
  </div>
  <div class="form-group">
    <label for="schedule" class="col-sm-2 control-label">Jadwal</label>
    <div class="col-sm-10">
      <select name="schedule_id" id="schedule" class="form-control">
        <option value="0">--Pilih Jadwal--</option>
        @foreach ($schedules as $schedule)
            <option value="{{$schedule->id}}">{{$schedule->code}}</option>
        @endforeach
      </select>
    </div>
  </div>
  <div class="form-group">
    <label for="active" class="col-sm-2 control-label">Status</label>
    <div class="col-sm-10">
      <label class="checkbox-inline">
        <input type="checkbox" id="active" name="active" value="1"> Aktif
      </label>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-12">
      <label class="checkbox-inline">
        <input type="checkbox" id="register" name="register" value="1"> Daftarkan untuk login di web ATFIS?<sup>*</sup>
      </label><br>
      <span class='label label-warning'><sup>*</sup>Login pengguna dan password menggunakan NIK</span>
    </div>
  </div>
</form>
<script>
  $('#birthday').datetimepicker({locale:'id',format: 'DD:MM:YYYY'});

</script>

resources/views/employee/edit.blade.php
<form action="{{URL::route('employee.update',array($employee->id))}}" class="form-horizontal" id="newForm">
<input name="_method" type="hidden" value="PUT">
<input type="hidden" name="_token" value="<?php echo csrf_token(); ?>">
  <div class="form-group">
    <label for="nik" class="col-sm-2 control-label">Nomor Induk </label>
    <div class="col-sm-10">
      <input type="hidden" name="id" value="{{$employee->id}}">
      <input type="text" class="form-control" id="nik" placeholder="Nomor Induk Pegawai"  name="nik" value="{{$employee->nik}}" readonly="readonly">
    </div>
  </div>
  <div class="form-group">
    <label for="name" class="col-sm-2 control-label">Nama </label>
    <div class="col-sm-10">
      <input type="text" class="form-control" id="name" placeholder="Nama Pegawai"  name="name" value="{{$employee->name}}" required>
    </div>
  </div>
  <div class="form-group">
    <label for="place_of_birth" class="col-sm-2 control-label">Tempat Lahir </label>
    <div class="col-sm-10">
      <input type="text" class="form-control" id="place_of_birth" placeholder="Tempat Lahir"  name="place_of_birth" value="{{$employee->place_of_birth}}" required>
    </div>
  </div>
  <div class="form-group">
    <label for="birthday" class="col-sm-2 control-label">Tanggal Lahir </label>
    <div class="col-sm-10">
      <input type="text" class="form-control" id="birthday" placeholder="Tempat Lahir"  name="birthday" value="{{date('d:m:Y',strtotime($employee->birthday))}}" required>
    </div>
  </div>
  <div class="form-group">
    <label for="address" class="col-sm-2 control-label">Alamat </label>
    <div class="col-sm-10">
      <textarea name="address" id="address" cols="30" rows="5" class="form-control" required>{{$employee->address}}</textarea>
    </div>
  </div>
  <div class="form-group">
    <label for="phone" class="col-sm-2 control-label">Telepon </label>
    <div class="col-sm-10">
      <input type="text" class="form-control" id="phone" placeholder="Nomor Telp"  name="phone" value="{{$employee->phone}}" required>
    </div>
  </div>
  <div class="form-group">
    <label for="email" class="col-sm-2 control-label">Email </label>
    <div class="col-sm-10">
      <input type="email" class="form-control" id="email" placeholder="Email Pegawai"  name="email" value="{{$employee->email}}" required>
    </div>
  </div>
  <div class="form-group">
    <label for="position" class="col-sm-2 control-label">Jabatan</label>
    <div class="col-sm-10">
      <select name="position_id" id="position" class="form-control">
        <option value="0">--Pilih Jabatan--</option>
        @foreach ($positions as $position)
            <option value="{{$position->id}}" {{($position->id == $employee->position_id)? 'selected' : '' }}  >{{$position->name}}</option>
        @endforeach
      </select>
    </div>
  </div>
  <div class="form-group">
    <label for="office" class="col-sm-2 control-label">Kantor</label>
    <div class="col-sm-10">
      <select name="office_id" id="office" class="form-control">
        <option value="0">--Pilih Kantor--</option>
        @foreach ($offices as $office)
            <option value="{{$office->id}}" {{($office->id == $employee->office_id)? 'selected' : '' }} >{{$office->name}}</option>
        @endforeach
      </select>
    </div>
  </div>
  <div class="form-group">
    <label for="schedule" class="col-sm-2 control-label">Jadwal</label>
    <div class="col-sm-10">
      <select name="schedule_id" id="schedule" class="form-control">
        <option value="0">--Pilih Jadwal--</option>
        @foreach ($schedules as $schedule)
            <option value="{{$schedule->id}}" {{($schedule->id == $employee->schedule_id)? 'selected' : '' }} >{{$schedule->code}}</option>
        @endforeach
      </select>
    </div>
  </div>
  <div class="form-group">
    <label for="active" class="col-sm-2 control-label">Status</label>
    <div class="col-sm-10">
      <label class="checkbox-inline">
        <input type="checkbox" id="active" name="active" value="1" {{($employee->active=='1')? 'checked' : '' }}> Aktif
      </label>
    </div>
  </div>
</form>
<script>
  $('#birthday').datetimepicker({locale:'id',format: 'DD:MM:YYYY'});

</script>

resources/views/employee/index.blade.php
@extends('app')

@section('content')
  <div class="row">
      <h2 class="page-header">Master Data <small>- Pegawai</small></h2>
      <p><a href="#" class="btn btn-sm btn-primary" id="btn-new">Tambah Pegawai</a></p>
  </div>
  {{-- Datatable --}}
  <table id="users-table" class="table table-condensed">
    <thead>
    <tr>
        <th>Id</th>
        <th>NIK</th>
        <th>Nama</th>
        <th>Jabatan</th>
        <th>Kantor</th>
        <th>Jadwal</th>
        <th>Status</th>
        <th>Operation</th>
    </tr>
    </thead>
  </table>
  
  {{-- Modal Form --}}
  <div class="modal" id="myModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title">Master Pegawai</h4>
            </div>
            <div class="modal-body"></div>
            <div id="response"></div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" id="save">Save changes</button>
            </div>
        </div>
    </div>
  </div>

  {{-- Show Form --}}
  <div class="modal" id="showModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title">Master Pegawai</h4>
            </div>
            <div class="modal-body"></div>
            <div id="response"></div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
  </div>

  {{-- Delete Form --}}
  <div class="modal" id="deleteModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title">Master Pegawai</h4>
            </div>
            <div class="modal-body">
              <h4>Are you sure ?</h4>
            </div>
            <div id="response"></div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-danger" id="delete">Delete</button>
            </div>
        </div>
    </div>
  </div>

@endsection

@section('javascript')
  <script>
  var table = $('#users-table').DataTable({
      processing: true,
      serverSide: true,
      ajax: '{{ url("employee/getData") }}',
      columns: [
          {data: 'id', name: 'id'},
          {data: 'nik', name: 'nik'},
          {data: 'name', name: 'name'},
          {data: 'position', name: 'position'},
          {data: 'office', name: 'office'},
          {data: 'schedule', name: 'schedule'},
          {data: 'active', name: 'active'},
          {data: 'operations', name: 'operations'},

      ]
  });
  table.ajax.reload();

</script>
@endsection

resources/views/employee/show.blade.php
<table class="table table-consended">
        <tr>

          <th>No Id</th><td>{{$employee->id}}</td>
        </tr>
        <tr>
          <th>No Induk</th><td>{{$employee->nik}}</td>
        </tr>
        <tr>
          <th>Nama</th><td>{{$employee->name}}</td>
        </tr>
        <tr>
          <th>Tempat Lahir</th><td>{{$employee->place_of_birth}}</td>
        </tr>
        <tr>
          <th>Tanggal Lahir</th><td>{{date('d - M - Y',strtotime($employee->birthday))}}</td>
        </tr>
        <tr>
          <th>Alamat</th><td>{{$employee->address}}</td>
        </tr>
        <tr>
          <th>Telp</th><td>{{$employee->phone}}</td>
        </tr>
        <tr>
          <th>Email</th><td>{{$employee->email}}</td>
        </tr>
        <tr>
          <th>Jabatan</th><td>{{$employee->position->name}}</td>
        </tr>
        <tr>
          <th>Kantor</th><td>{{$employee->office->name}}</td>
        </tr>
        <tr>
          <th>Jadwal</th><td>{{$employee->schedule->code}}</td>
        </tr>
        <tr>
          <th>Status</th><td>{{ ($employee->active==1) ? 'Aktif':'Tidak Aktif' }}</td>
        </tr>
        </table>